[netbricks]
name        = "TcpGenerator"
master_core = 0
pool_size   = 2048              # default 2048
cache_size  = 128                 # default 32
mbuf_cnt    = 65535             # default 65535, should be 2**N -1
cores       = [ 1, 2 ]
ports       = [ 
                    { name="7:00.0", rxd=4096, txd= 4096, cores = [ 1, 2 ], checksum = true, loopback = true, fdir = { pballoc="RteFdirPballoc256k", mode="RteFdirModePerfect", ipv4_mask= {src_ip="0.0.0.0", dst_ip="FFFFFFFF"}, src_port_mask="0", dst_port_mask="C000"} } ,
                    { name="kni:1", rxd=64, txd=64, cores = [0], k_cores = [0] }
              ] 
vdev        = [ "net_kni0" ]    # for use of vdev with KNI PMD, see https://dpdk.org/doc/guides/nics/kni.html

[trafficengine]

engine      = { namespace="nskni", mac="a0:36:9f:82:9c:fc", ipnet="192.168.222.2/24", port=20001, timeouts= { established= 4000 }, cps_limit=230000, max_open= 2000, detailed_records= true, fin_by_client= 1000, fin_by_server= 1 }

targets      = [ { id = "tcpgen_0", ip = "192.168.222.2", mac="a0:36:9f:82:9c:fc" , port = 65535 },
                 { id = "tcpgen_1", ip = "192.168.222.2", mac="a0:36:9f:82:9c:fc" , port = 49151 },
#                 { id = "tcpgen_2", ip = "192.168.222.2", mac="a0:36:9f:82:9c:fc" , port = 32767 },
#                 { id = "tcpgen_3", ip = "192.168.222.2", mac="a0:36:9f:82:9c:fc" , port = 16383 },
              ]

test_size   = 200000