[netbricks]
name        = "TcpGenerator"
master_core = 0
pool_size   = 2048              # default 2048
cache_size  = 32                # default 32
cores       = [ 1, 2, 3 ]
ports       = [
                    { name="a:00.0", rxd= 1024, txd= 1024, cores = [1, 2, 3], driver= "I40e", fdir = { pballoc="RteFdirPballoc256k", mode="RteFdirModePerfect", ipv4_mask= {src_ip="0.0.0.0", dst_ip="FFFFFFFF"}, src_port_mask="0", dst_port_mask="C000"}},

                    { name="kni:1", rxd=64, txd=64, cores = [0], k_cores = [0] }
              ] 
vdev        = [ "net_kni0" ]    # for use of vdev with KNI PMD, see https://dpdk.org/doc/guides/nics/kni.html

[trafficengine]

engine      = { flow_steering= "Ip", namespace="nskni", mac="3c:fd:fe:9e:ce:4c", ipnet="192.168.222.1/24", port=20001, timeouts= { established= 10000 }, cps_limit=200000 }

targets      = [ { id = "tcpgen_0", ip = "192.168.222.2", mac="a0:36:9f:82:9c:fc" , port = 65535 },
                 { id = "tcpgen_1", ip = "192.168.222.3", mac="a0:36:9f:82:9c:fc" , port = 65535 },
                 { id = "tcpgen_2", ip = "192.168.222.4", mac="a0:36:9f:82:9c:fc" , port = 65535 },
#                 { id = "tcpgen_3", ip = "192.168.222.2", mac="a0:36:9f:82:9c:fc" , port = 16383 },
              ]

test_size   = 48000
