[netbricks]
name        = "TcpGenerator"
master_core = 0
pool_size   = 2048              # default 2048
cache_size  = 128               # default 32
cores       = [ 1, 2, 3, 4 ]
ports       = [ 
                    { name="a:00.0", rxd= 1024, txd= 4096, cores = [ 1, 2, 3, 4 ], driver="I40e", fdir = { pballoc="RteFdirPballoc256k", mode="RteFdirModePerfect", ipv4_mask= {src_ip="0.0.0.0", dst_ip="FFFFFFFF"}, src_port_mask="0", dst_port_mask="8000"} } ,
                    { name="kni:1", rxd=64, txd=64, cores = [0], k_cores = [0] }
              ] 
vdev        = [ "net_kni0" ]    # for use of vdev with KNI PMD, see https://dpdk.org/doc/guides/nics/kni.html

[trafficengine]

engine      = { flow_steering= "Ip", namespace="nskni", mac="3c:fd:fe:9e:ce:4c", ipnet="192.168.222.2/24", port=20001, timeouts= { established= 10000 }, cps_limit= 90000  }
targets     = [ { id = "proxy", ip = "192.168.222.8", mac="a0:36:9f:82:9c:fc", port = 999 },
              ]
test_size   = 22500
